# Generated by Django 5.2.8 on 2026-04-16 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesInvoice",
            fields=[],
            options={
                "verbose_name": "Sales",
                "verbose_name_plural": "Sales",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("sales.sales",),
        ),
        migrations.CreateModel(
            name="SalesReturn",
            fields=[],
            options={
                "verbose_name": "Sales Return",
                "verbose_name_plural": "Sales Returns",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("sales.sales",),
        ),
        migrations.AlterModelOptions(
            name="sales",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "Sale",
                "verbose_name_plural": "Sales",
            },
        ),
        migrations.AddField(
            model_name="sales",
            name="ref_sale",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="sales.sales"
            ),
        ),
        migrations.AddField(
            model_name="sales",
            name="sale_type",
            field=models.CharField(
                choices=[("SALE", "Sale"), ("RETURN", "Return")], default="SALE", max_length=20
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="salesitem",
            name="ref_sale_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="sales.salesitem",
            ),
        ),
    ]
