# Generated by Django 5.2.8 on 2026-04-16 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_salesinvoice_salesreturn_alter_sales_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salesreturn",
            options={"verbose_name": "Sale Return", "verbose_name_plural": "Sale Returns"},
        ),
    ]
