# Generated by Django 5.2.8 on 2026-04-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_alter_salesitem_gross_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="sale_no_full",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
