# Generated by Django 5.2.8 on 2026-04-13 10:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "Item", "verbose_name_plural": "Item Setup"},
        ),
        migrations.AlterModelOptions(
            name="itembrand",
            options={"verbose_name": "Item Brand", "verbose_name_plural": "Item Brands"},
        ),
        migrations.AlterModelOptions(
            name="itemcategory",
            options={"verbose_name": "Item Category", "verbose_name_plural": "Item Categories"},
        ),
        migrations.AlterModelOptions(
            name="itemunit",
            options={"verbose_name": "Item Unit", "verbose_name_plural": "Item Units"},
        ),
        migrations.AlterModelOptions(
            name="warehouse",
            options={"verbose_name": "Warehouse", "verbose_name_plural": "Warehouses"},
        ),
        migrations.CreateModel(
            name="StockLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="date updated")),
                ("is_active", models.BooleanField(default=True)),
                ("direction", models.SmallIntegerField(choices=[(1, "IN"), (-1, "OUT")])),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "Purchase"),
                            ("SALES", "Sales"),
                            ("OPENING_STOCK", "Opening Stock"),
                            ("LOST", "Lost"),
                            ("DAMAGED", "Damaged"),
                            ("EXPIRED", "Expired"),
                            ("OTHER", "Other"),
                            ("ADJUSTMENT", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("remarks", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_ledgers",
                        to="inventory.item",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
