# Generated by Django 5.2.8 on 2026-04-13 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_item_options_alter_itembrand_options_and_more"),
        ("purchase", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockledger",
            name="purchase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_entries",
                to="purchase.purchase",
            ),
        ),
        migrations.AddField(
            model_name="stockledger",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_ledgers",
                to="inventory.warehouse",
            ),
        ),
        migrations.AddIndex(
            model_name="stockledger",
            index=models.Index(fields=["item"], name="inventory_s_item_id_4f84ea_idx"),
        ),
        migrations.AddIndex(
            model_name="stockledger",
            index=models.Index(fields=["warehouse"], name="inventory_s_warehou_a465fe_idx"),
        ),
        migrations.AddIndex(
            model_name="stockledger",
            index=models.Index(fields=["movement_type"], name="inventory_s_movemen_553342_idx"),
        ),
        migrations.AddIndex(
            model_name="stockledger",
            index=models.Index(fields=["purchase"], name="inventory_s_purchas_062775_idx"),
        ),
    ]
