# Generated by Django 5.2.8 on 2026-04-16 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_stockledger_purchase_stockledger_warehouse_and_more"),
        ("purchase", "0003_purchaseinvoice_purchasereturn_and_more"),
        ("sales", "0003_alter_salesreturn_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stockledger",
            name="sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_entries",
                to="sales.sales",
            ),
        ),
        migrations.AddIndex(
            model_name="stockledger",
            index=models.Index(fields=["sale"], name="inventory_s_sale_id_adbcfc_idx"),
        ),
    ]
