# Generated by Django 5.2.8 on 2026-05-11 10:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="date updated")),
                ("is_active", models.BooleanField(default=True)),
                ("full_name", models.CharField(max_length=255)),
                ("phone_no", models.CharField(blank=True, max_length=20)),
                ("phone_no_alt", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ("full_name",),
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="date updated")),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("PCS", "Pcs"),
                            ("BOX", "Box"),
                            ("STRIP", "Strip"),
                            ("TABLET", "Tablet"),
                            ("ML", "Ml"),
                            ("L", "L"),
                            ("G", "G"),
                            ("KG", "Kg"),
                        ],
                        default="PCS",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Item Setup",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="date updated")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order_type",
                    models.CharField(
                        choices=[("ORDER", "Order"), ("RETURN", "Return")], max_length=20
                    ),
                ),
                ("order_no", models.PositiveBigIntegerField()),
                ("order_no_full", models.CharField(max_length=50, unique=True)),
                ("bill_no", models.CharField(blank=True, max_length=50)),
                ("bill_date", models.DateField(blank=True, null=True)),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "sub_total",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "grand_total",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=500)),
                ("notes", models.TextField(blank=True)),
                (
                    "is_urgent",
                    models.BooleanField(default=False, help_text="Is this a priority order?"),
                ),
                ("deadline_date", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_orders",
                        to="order_management.customer",
                    ),
                ),
                (
                    "ref_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="order_management.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="OrderInvoice",
            fields=[],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Order",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("order_management.order",),
        ),
        migrations.CreateModel(
            name="OrderReturn",
            fields=[],
            options={
                "verbose_name": "Order Return",
                "verbose_name_plural": "Order Returns",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("order_management.order",),
        ),
        migrations.CreateModel(
            name="OrderStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="date updated")),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "color",
                    models.CharField(
                        default="#6B7280",
                        help_text="Hex color code for frontend badge display",
                        max_length=20,
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        default=0, help_text="Controls ordering of statuses in pipeline"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Default status when creating order"
                    ),
                ),
                (
                    "is_terminal",
                    models.BooleanField(
                        default=False, help_text="Final stage status like Delivered or Cancelled"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Status",
                "verbose_name_plural": "Order Statuses",
                "ordering": ["sequence", "id"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="order_management.orderstatus",
            ),
        ),
        migrations.CreateModel(
            name="OrderAdditionalCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="date updated")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("remarks", models.CharField(blank=True, max_length=50)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="additional_charges",
                        to="order_management.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Additional Charge",
                "verbose_name_plural": "Additional Charges",
                "indexes": [models.Index(fields=["order"], name="order_manag_order_i_c2a2d1_idx")],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="date updated")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "discount_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "gross_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="order_management.item"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="order_management.order",
                    ),
                ),
                (
                    "ref_order_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="order_management.orderitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["order"], name="order_manag_order_i_2bbee7_idx"),
                    models.Index(fields=["item"], name="order_manag_item_id_43f78e_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("order", "item"), name="unique_item_per_order")
                ],
            },
        ),
        migrations.CreateModel(
            name="OrderPaymentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="date updated")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("remarks", models.CharField(blank=True, max_length=50)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_details",
                        to="order_management.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Detail",
                "verbose_name_plural": "Payment Details",
                "indexes": [models.Index(fields=["order"], name="order_manag_order_i_eca475_idx")],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["customer"], name="order_manag_custome_e5698e_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["order_no_full"], name="order_manag_order_n_eadc0f_idx"),
        ),
    ]
