# Generated by Django 5.2.8 on 2026-05-11 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_management", "0002_alter_orderinvoice_options_paymentmethod_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrderReturn",
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="item_orders",
                to="order_management.item",
            ),
        ),
        migrations.AlterField(
            model_name="orderpaymentdetail",
            name="payment_mode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_mode_payment_details",
                to="order_management.paymentmethod",
            ),
        ),
    ]
