# Generated by Django 6.0.4 on 2026-04-10 06:09

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="is_primary",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="owner",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="domain",
            name="domain",
            field=models.CharField(db_index=True, max_length=253, unique=True),
        ),
        migrations.AlterField(
            model_name="domain",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domains",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="schema_name",
            field=models.CharField(
                db_index=True,
                max_length=63,
                unique=True,
                validators=[django_tenants.postgresql_backend.base._check_schema_name],
            ),
        ),
    ]
