# Generated by Django 5.2.8 on 2026-05-11 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expense_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={"verbose_name": "Expense", "verbose_name_plural": "Expenses"},
        ),
        migrations.AlterModelOptions(
            name="expensecategory",
            options={
                "verbose_name": "Expense Category",
                "verbose_name_plural": "Expense Categories",
            },
        ),
    ]
