# Generated by Django 5.2.8 on 2026-05-11 15:54

import src.libs.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense_management", "0002_alter_expense_options_alter_expensecategory_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenseattachment",
            name="file",
            field=models.FileField(upload_to=src.libs.storage.tenant_media_path),
        ),
    ]
