# Generated by Django 6.0.4 on 2026-04-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TenantResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("data", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Tenant Resource",
                "verbose_name_plural": "Tenant Resources",
            },
        ),
    ]
