# Generated by Django 5.2.8 on 2026-04-13 10:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("inventory", "0002_alter_item_options_alter_itembrand_options_and_more"),
        ("party_management", "0001_initialll"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="date updated")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "pay_type",
                    models.CharField(
                        choices=[("CASH", "Cash"), ("CREDIT", "Credit")], max_length=20
                    ),
                ),
                ("purchase_no", models.PositiveBigIntegerField()),
                ("purchase_no_full", models.CharField(max_length=20, unique=True)),
                ("bill_no", models.CharField(max_length=50, unique=True)),
                ("bill_date", models.DateField()),
                ("total_discount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_tax", models.DecimalField(decimal_places=2, max_digits=12)),
                ("sub_total", models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, editable=False, max_digits=12),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="party_management.supplier",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["-bill_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseAdditionalCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="date updated")),
                ("is_active", models.BooleanField(default=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("remarks", models.CharField(blank=True, max_length=50)),
                (
                    "charge_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.additionalchargetype"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="additional_charges",
                        to="purchase.purchase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="date updated")),
                ("is_active", models.BooleanField(default=True)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=12)),
                ("tax_rate", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("tax_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("discount_rate", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "gross_amount",
                    models.DecimalField(decimal_places=2, editable=False, max_digits=12),
                ),
                (
                    "net_amount",
                    models.DecimalField(decimal_places=2, editable=False, max_digits=12),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="inventory.item"
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchase.purchase",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PurchasePaymentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="date updated")),
                ("is_active", models.BooleanField(default=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "payment_mode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.paymentmethod"
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_details",
                        to="purchase.purchase",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(fields=["bill_no"], name="purchase_pu_bill_no_2bc0cc_idx"),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(fields=["supplier"], name="purchase_pu_supplie_b1e56b_idx"),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(fields=["bill_date"], name="purchase_pu_bill_da_986ce3_idx"),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(fields=["purchase_no_full"], name="purchase_pu_purchas_3497b2_idx"),
        ),
        migrations.AddIndex(
            model_name="purchaseadditionalcharge",
            index=models.Index(fields=["purchase"], name="purchase_pu_purchas_7c6fcc_idx"),
        ),
        migrations.AddIndex(
            model_name="purchaseadditionalcharge",
            index=models.Index(fields=["charge_type"], name="purchase_pu_charge__c7fcb3_idx"),
        ),
        migrations.AddIndex(
            model_name="purchaseitem",
            index=models.Index(fields=["purchase"], name="purchase_pu_purchas_c83379_idx"),
        ),
        migrations.AddIndex(
            model_name="purchaseitem",
            index=models.Index(fields=["item"], name="purchase_pu_item_id_319c0a_idx"),
        ),
        migrations.AddConstraint(
            model_name="purchaseitem",
            constraint=models.UniqueConstraint(
                fields=("purchase", "item"), name="unique_item_per_purchase"
            ),
        ),
        migrations.AddIndex(
            model_name="purchasepaymentdetail",
            index=models.Index(fields=["purchase"], name="purchase_pu_purchas_615394_idx"),
        ),
        migrations.AddIndex(
            model_name="purchasepaymentdetail",
            index=models.Index(fields=["payment_mode"], name="purchase_pu_payment_615c21_idx"),
        ),
    ]
