# Generated by Django 5.2.8 on 2026-04-16 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchaseadditionalcharge",
            options={
                "verbose_name": "Additional Charge",
                "verbose_name_plural": "Additional Charges",
            },
        ),
        migrations.AlterModelOptions(
            name="purchaseitem",
            options={
                "ordering": ["id"],
                "verbose_name": "Purchase Item",
                "verbose_name_plural": "Purchase Items",
            },
        ),
        migrations.AlterModelOptions(
            name="purchasepaymentdetail",
            options={"verbose_name": "Payment Detail", "verbose_name_plural": "Payment Details"},
        ),
        migrations.AddField(
            model_name="purchasepaymentdetail",
            name="remarks",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="grand_total",
            field=models.DecimalField(
                decimal_places=2,
                editable=False,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="sub_total",
            field=models.DecimalField(
                decimal_places=2,
                editable=False,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="total_discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="total_tax",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="purchaseadditionalcharge",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="discount_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="gross_amount",
            field=models.DecimalField(
                decimal_places=2,
                editable=False,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="net_amount",
            field=models.DecimalField(
                decimal_places=2,
                editable=False,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="purchasepaymentdetail",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
