# Generated by Django 5.2.8 on 2026-04-16 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0002_alter_purchaseadditionalcharge_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseInvoice",
            fields=[],
            options={
                "verbose_name": "Purchase",
                "verbose_name_plural": "Purchases",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("purchase.purchase",),
        ),
        migrations.CreateModel(
            name="PurchaseReturn",
            fields=[],
            options={
                "verbose_name": "Purchase Return",
                "verbose_name_plural": "Purchase Returns",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("purchase.purchase",),
        ),
        migrations.AddField(
            model_name="purchase",
            name="purchase_type",
            field=models.CharField(
                choices=[("PURCHASE", "Purchase"), ("RETURN", "Return")],
                default="PURCHASE",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purchase",
            name="ref_purchase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="purchase.purchase",
            ),
        ),
        migrations.AddField(
            model_name="purchaseitem",
            name="ref_purchase_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="purchase.purchaseitem",
            ),
        ),
    ]
