# Generated by Django 5.2.8 on 2026-04-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0003_purchaseinvoice_purchasereturn_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="purchase_no_full",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
