# Generated by Django 5.2.8 on 2026-04-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0004_alter_purchase_purchase_no_full"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="pay_type",
            field=models.CharField(choices=[("CASH", "Cash"), ("CREDIT", "Credit")], max_length=50),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="purchase_type",
            field=models.CharField(
                choices=[("PURCHASE", "Purchase"), ("RETURN", "Return")], max_length=50
            ),
        ),
    ]
