# Generated by Django 5.2.8 on 2026-04-17 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0005_alter_purchase_pay_type_alter_purchase_purchase_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseitem",
            name="gross_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="net_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
