# Generated by Django 5.2.8 on 2026-04-16 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="additionalchargetype",
            options={
                "verbose_name": "Additional Charge Type",
                "verbose_name_plural": "Additional Charge Types",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentmethod",
            options={"verbose_name": "Payment Method", "verbose_name_plural": "Payment Methods"},
        ),
    ]
